% read the data from the standard spreadsheet reporting river observations
header = all(1,:); for i=1:length(header); if isnan(header{i}); header{i} = 'NaN'; end; end

% (1) read in the name and additional information fields
river.info.name = all(2:end,ismember(header,'Name'));
river.info.samplenumber = all(2:end,ismember(header,'SampleNumber'));
river.info.extrafield1  = all(2:end,ismember(header,'ExtraField1')); 
river.info.extrafield2  = all(2:end,ismember(header,'ExtraField2'));
river.info.extrafield3  = all(2:end,ismember(header,'ExtraField3'));
river.info.extrafield4  = all(2:end,ismember(header,'ExtraField4'));
river.info.extrafield5  = all(2:end,ismember(header,'ExtraField5'));
if sum(ismember(header,'ClCritical'))                >0; rawClCrin       = all(2:end,ismember(header,'ClCritical'));                upClCrin       = []; for i=1:length(rawClCrin);       if isnumeric(rawClCrin{i});       upClCrin(i,1)       = rawClCrin{i};       else; upClCrin(i,1)       = NaN; end; end; river.observations.ClCr            = upClCrin;       river.model_variable.ClCr          = river.observations.ClCr;                               end          
if sum(ismember(header,'Latitude_oN'))               >0; rawlatdin       = all(2:end,ismember(header,'Latitude_oN'));               uplatdin       = []; for i=1:length(rawlatdin);       if isnumeric(rawlatdin{i});       uplatdin(i,1)       = rawlatdin{i};       else; uplatdin(i,1)       = NaN; end; end; river.observations.latd            = uplatdin;                                                                                                   end          
if sum(ismember(header,'Longitude_oE'))              >0; rawlongin       = all(2:end,ismember(header,'Longitude_oE'));              uplongin       = []; for i=1:length(rawlongin);       if isnumeric(rawlongin{i});       uplongin(i,1)       = rawlongin{i};       else; uplongin(i,1)       = NaN; end; end; river.observations.long            = uplongin;                                                                                                   end          

% (2) read in the observations
if sum(ismember(header,'ALK_uM'))                    >0; rawALKin        = all(2:end,ismember(header,'ALK_uM'));                    upALKin        = []; for i=1:length(rawALKin);        if isnumeric(rawALKin{i});        upALKin(i,1)        = rawALKin{i};        else; upALKin(i,1)        = NaN; end; end; river.observations.ALK_conc        = upALKin;        river.observations.ALK_equi        = river.observations.ALK_conc        * conc2equi.ALK;    end
if sum(ismember(header,'DIC_uM'))                    >0; rawDICin        = all(2:end,ismember(header,'DIC_uM'));                    upDICin        = []; for i=1:length(rawDICin);        if isnumeric(rawDICin{i});        upDICin(i,1)        = rawDICin{i};        else; upDICin(i,1)        = NaN; end; end; river.observations.DIC_conc        = upDICin;        river.observations.DIC_equi        = river.observations.DIC_conc        * conc2equi.DIC;    end
if sum(ismember(header,'Ca_uM'))                     >0; rawCain         = all(2:end,ismember(header,'Ca_uM'));                     upCain         = []; for i=1:length(rawCain);         if isnumeric(rawCain{i});         upCain(i,1)         = rawCain{i};         else; upCain(i,1)         = NaN; end; end; river.observations.Ca_conc         = upCain;         river.observations.Ca_equi         = river.observations.Ca_conc         * conc2equi.Ca;     end
if sum(ismember(header,'Mg_uM'))                     >0; rawMgin         = all(2:end,ismember(header,'Mg_uM'));                     upMgin         = []; for i=1:length(rawMgin);         if isnumeric(rawMgin{i});         upMgin(i,1)         = rawMgin{i};         else; upMgin(i,1)         = NaN; end; end; river.observations.Mg_conc         = upMgin;         river.observations.Mg_equi         = river.observations.Mg_conc         * conc2equi.Mg;     end
if sum(ismember(header,'Na_uM'))                     >0; rawNain         = all(2:end,ismember(header,'Na_uM'));                     upNain         = []; for i=1:length(rawNain);         if isnumeric(rawNain{i});         upNain(i,1)         = rawNain{i};         else; upNain(i,1)         = NaN; end; end; river.observations.Na_conc         = upNain;         river.observations.Na_equi         = river.observations.Na_conc         * conc2equi.Na;     end
if sum(ismember(header,'K_uM'))                      >0; rawKin          = all(2:end,ismember(header,'K_uM'));                      upKin          = []; for i=1:length(rawKin);          if isnumeric(rawKin{i});          upKin(i,1)          = rawKin{i};          else; upKin(i,1)          = NaN; end; end; river.observations.K_conc          = upKin;          river.observations.K_equi          = river.observations.K_conc          * conc2equi.K;      end
if sum(ismember(header,'Sr_uM'))                     >0; rawSrin         = all(2:end,ismember(header,'Sr_uM'));                     upSrin         = []; for i=1:length(rawSrin);         if isnumeric(rawSrin{i});         upSrin(i,1)         = rawSrin{i};         else; upSrin(i,1)         = NaN; end; end; river.observations.Sr_conc         = upSrin;         river.observations.Sr_equi         = river.observations.Sr_conc         * conc2equi.Sr;     end
if sum(ismember(header,'Cl_uM'))                     >0; rawClin         = all(2:end,ismember(header,'Cl_uM'));                     upClin         = []; for i=1:length(rawClin);         if isnumeric(rawClin{i});         upClin(i,1)         = rawClin{i};         else; upClin(i,1)         = NaN; end; end; river.observations.Cl_conc         = upClin;         river.observations.Cl_equi         = river.observations.Cl_conc         * conc2equi.Cl;     end
if sum(ismember(header,'SO4_uM'))                    >0; rawSO4in        = all(2:end,ismember(header,'SO4_uM'));                    upSO4in        = []; for i=1:length(rawSO4in);        if isnumeric(rawSO4in{i});        upSO4in(i,1)        = rawSO4in{i};        else; upSO4in(i,1)        = NaN; end; end; river.observations.SO4_conc        = upSO4in;        river.observations.SO4_equi        = river.observations.SO4_conc        * conc2equi.SO4;    end
if sum(ismember(header,'NO3_uM'))                    >0; rawNO3in        = all(2:end,ismember(header,'NO3_uM'));                    upNO3in        = []; for i=1:length(rawNO3in);        if isnumeric(rawNO3in{i});        upNO3in(i,1)        = rawNO3in{i};        else; upNO3in(i,1)        = NaN; end; end; river.observations.NO3_conc        = upNO3in;        river.observations.NO3_equi        = river.observations.NO3_conc        * conc2equi.NO3;    end
if sum(ismember(header,'PO4_uM'))                    >0; rawPO4in        = all(2:end,ismember(header,'PO4_uM'));                    upPO4in        = []; for i=1:length(rawPO4in);        if isnumeric(rawPO4in{i});        upPO4in(i,1)        = rawPO4in{i};        else; upPO4in(i,1)        = NaN; end; end; river.observations.PO4_conc        = upPO4in;        river.observations.PO4_equi        = river.observations.PO4_conc        * conc2equi.PO4;    end
if sum(ismember(header,'Si_uM'))                     >0; rawSiin         = all(2:end,ismember(header,'Si_uM'));                     upSiin         = []; for i=1:length(rawSiin);         if isnumeric(rawSiin{i});         upSiin(i,1)         = rawSiin{i};         else; upSiin(i,1)         = NaN; end; end; river.observations.Si_conc         = upSiin;         river.observations.Si_equi         = river.observations.Si_conc         * conc2equi.Si;     end 
if sum(ismember(header,'Ge_uM'))                     >0; rawGein         = all(2:end,ismember(header,'Ge_uM'));                     upGein         = []; for i=1:length(rawGein);         if isnumeric(rawGein{i});         upGein(i,1)         = rawGein{i};         else; upGein(i,1)         = NaN; end; end; river.observations.Ge_conc         = upGein;         river.observations.Ge_equi         = river.observations.Ge_conc         * conc2equi.Ge;     end 
if sum(ismember(header,'Li_uM'))                     >0; rawLiin         = all(2:end,ismember(header,'Li_uM'));                     upLiin         = []; for i=1:length(rawLiin);         if isnumeric(rawLiin{i});         upLiin(i,1)         = rawLiin{i};         else; upLiin(i,1)         = NaN; end; end; river.observations.Li_conc         = upLiin;         river.observations.Li_equi         = river.observations.Li_conc         * conc2equi.Li;     end       
if sum(ismember(header,'F_uM'))                      >0; rawFin          = all(2:end,ismember(header,'F_uM'));                      upFin          = []; for i=1:length(rawFin);          if isnumeric(rawFin{i});          upFin(i,1)          = rawFin{i};          else; upFin(i,1)          = NaN; end; end; river.observations.F_conc          = upFin;          river.observations.F_equi          = river.observations.F_conc          * conc2equi.F;      end        
if sum(ismember(header,'Fe_pM'))                     >0; rawFein         = all(2:end,ismember(header,'Fe_pM'));                     upFein         = []; for i=1:length(rawFein);         if isnumeric(rawFein{i});         upFein(i,1)         = rawFein{i};         else; upFein(i,1)         = NaN; end; end; river.observations.Fe_conc         = upFein/1e6;     river.observations.Fe_equi         = river.observations.Fe_conc         * conc2equi.Fe;     end        
if sum(ismember(header,'B_pM'))                      >0; rawBin          = all(2:end,ismember(header,'B_pM'));                      upBin          = []; for i=1:length(rawBin);          if isnumeric(rawBin{i});          upBin(i,1)          = rawBin{i};          else; upBin(i,1)          = NaN; end; end; river.observations.B_conc          = upBin/1e6;      river.observations.B_equi          = river.observations.B_conc          * conc2equi.B;      end        
if sum(ismember(header,'Re_pM'))                     >0; rawRein         = all(2:end,ismember(header,'Re_pM'));                     upRein         = []; for i=1:length(rawRein);         if isnumeric(rawRein{i});         upRein(i,1)         = rawRein{i};         else; upRein(i,1)         = NaN; end; end; river.observations.Re_conc         = upRein/1e6;     river.observations.Re_equi         = river.observations.Re_conc         * conc2equi.Re;     end       
if sum(ismember(header,'Mo_pM'))                     >0; rawMoin         = all(2:end,ismember(header,'Mo_pM'));                     upMoin         = []; for i=1:length(rawMoin);         if isnumeric(rawMoin{i});         upMoin(i,1)         = rawMoin{i};         else; upMoin(i,1)         = NaN; end; end; river.observations.Mo_conc         = upMoin/1e6;     river.observations.Mo_equi         = river.observations.Mo_conc         * conc2equi.Mo;     end       
if sum(ismember(header,'Os_pM'))                     >0; rawOsin         = all(2:end,ismember(header,'Os_pM'));                     upOsin         = []; for i=1:length(rawOsin);         if isnumeric(rawOsin{i});         upOsin(i,1)         = rawOsin{i};         else; upOsin(i,1)         = NaN; end; end; river.observations.Os_conc         = upOsin/1e6;     river.observations.Os_equi         = river.observations.Os_conc         * conc2equi.Os;     end       
if sum(ismember(header,'HCO3_uM'))                   >0; rawHCO3in       = all(2:end,ismember(header,'HCO3_uM'));                   upHCO3in       = []; for i=1:length(rawHCO3in);       if isnumeric(rawHCO3in{i});       upHCO3in(i,1)       = rawHCO3in{i};       else; upHCO3in(i,1)       = NaN; end; end; river.observations.HCO3_conc       = upHCO3in;       river.observations.HCO3_equi       = river.observations.HCO3_conc       * conc2equi.HCO3;   end       
if sum(ismember(header,'d34S_permil'))               >0; rawd34Sin       = all(2:end,ismember(header,'d34S_permil'));               upd34Sin       = []; for i=1:length(rawd34Sin);       if isnumeric(rawd34Sin{i});       upd34Sin(i,1)       = rawd34Sin{i};       else; upd34Sin(i,1)       = NaN; end; end; river.observations.d34S_conc       = upd34Sin;       river.observations.d34S_equi       = river.observations.d34S_conc       * conc2equi.d34S;   end       
if sum(ismember(header,'d18O_permil'))               >0; rawd18Oin       = all(2:end,ismember(header,'d18O_permil'));               upd18Oin       = []; for i=1:length(rawd18Oin);       if isnumeric(rawd18Oin{i});       upd18Oin(i,1)       = rawd18Oin{i};       else; upd18Oin(i,1)       = NaN; end; end; river.observations.d18O_conc       = upd18Oin;       river.observations.d18O_equi       = river.observations.d18O_conc       * conc2equi.d18O;   end       
if sum(ismember(header,'d7Li_permil'))               >0; rawd7Liin       = all(2:end,ismember(header,'d7Li_permil'));               upd7Liin       = []; for i=1:length(rawd7Liin);       if isnumeric(rawd7Liin{i});       upd7Liin(i,1)       = rawd7Liin{i};       else; upd7Liin(i,1)       = NaN; end; end; river.observations.d7Li_conc       = upd7Liin;       river.observations.d7Li_equi       = river.observations.d7Li_conc       * conc2equi.d7Li;   end                 
if sum(ismember(header,'d26Mg_permil'))              >0; rawd26Mgin      = all(2:end,ismember(header,'d26Mg_permil'));              upd26Mgin      = []; for i=1:length(rawd26Mgin);      if isnumeric(rawd26Mgin{i});      upd26Mgin(i,1)      = rawd26Mgin{i};      else; upd26Mgin(i,1)      = NaN; end; end; river.observations.d26Mg_conc      = upd26Mgin;      river.observations.d26Mg_equi      = river.observations.d26Mg_conc      * conc2equi.d26Mg;  end                
if sum(ismember(header,'d30Si_permil'))              >0; rawd30Siin      = all(2:end,ismember(header,'d30Si_permil'));              upd30Siin      = []; for i=1:length(rawd30Siin);      if isnumeric(rawd30Siin{i});      upd30Siin(i,1)      = rawd30Siin{i};      else; upd30Siin(i,1)      = NaN; end; end; river.observations.d30Si_conc      = upd30Siin;      river.observations.d30Si_equi      = river.observations.d30Si_conc      * conc2equi.d30Si;  end                
if sum(ismember(header,'d42Ca_permil'))              >0; rawd42Cain      = all(2:end,ismember(header,'d42Ca_permil'));              upd42Cain      = []; for i=1:length(rawd42Cain);      if isnumeric(rawd42Cain{i});      upd42Cain(i,1)      = rawd42Cain{i};      else; upd42Cain(i,1)      = NaN; end; end; river.observations.d42Ca_conc      = upd42Cain;      river.observations.d42Ca_equi      = river.observations.d42Ca_conc      * conc2equi.d42Ca;  end                
if sum(ismember(header,'d44Ca_permil'))              >0; rawd44Cain      = all(2:end,ismember(header,'d44Ca_permil'));              upd44Cain      = []; for i=1:length(rawd44Cain);      if isnumeric(rawd44Cain{i});      upd44Cain(i,1)      = rawd44Cain{i};      else; upd44Cain(i,1)      = NaN; end; end; river.observations.d44Ca_conc      = upd44Cain;      river.observations.d44Ca_equi      = river.observations.d44Ca_conc      * conc2equi.d44Ca;  end                
if sum(ismember(header,'d56Fe_permil'))              >0; rawd56Fein      = all(2:end,ismember(header,'d56Fe_permil'));              upd56Fein      = []; for i=1:length(rawd56Fein);      if isnumeric(rawd56Fein{i});      upd56Fein(i,1)      = rawd56Fein{i};      else; upd56Fein(i,1)      = NaN; end; end; river.observations.d56Fe_conc      = upd56Fein;      river.observations.d56Fe_equi      = river.observations.d56Fe_conc      * conc2equi.d56Fe;  end                
if sum(ismember(header,'Sr8786_ratio'))              >0; rawSr8786in     = all(2:end,ismember(header,'Sr8786_ratio'));              upSr8786in     = []; for i=1:length(rawSr8786in);     if isnumeric(rawSr8786in{i});     upSr8786in(i,1)     = rawSr8786in{i};     else; upSr8786in(i,1)     = NaN; end; end; river.observations.Sr8786_conc     = upSr8786in;     river.observations.Sr8786_equi     = river.observations.Sr8786_conc     * conc2equi.Sr8786; end               
if sum(ismember(header,'d98Mo_permil'))              >0; rawd98Moin      = all(2:end,ismember(header,'d98Mo_permil'));              upd98Moin      = []; for i=1:length(rawd98Moin);      if isnumeric(rawd98Moin{i});      upd98Moin(i,1)      = rawd98Moin{i};      else; upd98Moin(i,1)      = NaN; end; end; river.observations.d98Mo_conc      = upd98Moin;      river.observations.d98Mo_equi      = river.observations.d98Mo_conc      * conc2equi.d98Mo;  end                
if sum(ismember(header,'Os187188_ratio'))            >0; rawOs8788in     = all(2:end,ismember(header,'Os187188_ratio'));            upOs8788in     = []; for i=1:length(rawOs8788in);     if isnumeric(rawOs8788in{i});     upOs8788in(i,1)     = rawOs8788in{i};     else; upOs8788in(i,1)     = NaN; end; end; river.observations.Os8788_conc     = upOs8788in;     river.observations.Os8788_equi     = river.observations.Os8788_conc     * conc2equi.Os8788; end                
if sum(ismember(header,'d13C_permil'))               >0; rawd13Cin       = all(2:end,ismember(header,'d13C_permil'));               upd13Cin       = []; for i=1:length(rawd13Cin);       if isnumeric(rawd13Cin{i});       upd13Cin(i,1)       = rawd13Cin{i};       else; upd13Cin(i,1)       = NaN; end; end; river.observations.d13C_conc       = upd13Cin;       river.observations.d13C_equi       = river.observations.d13C_conc       * conc2equi.d13C;   end                
if sum(ismember(header,'Fmod'))                      >0; rawFmodin       = all(2:end,ismember(header,'Fmod'));                      upFmodin       = []; for i=1:length(rawFmodin);       if isnumeric(rawFmodin{i});       upFmodin(i,1)       = rawFmodin{i};       else; upFmodin(i,1)       = NaN; end; end; river.observations.Fmod_conc       = upFmodin;       river.observations.Fmod_equi       = river.observations.Fmod_conc       * conc2equi.Fmod;   end                

% (3) read in the observation errors
if sum(ismember(header,'Unc_ALK_uM_1sigma'))         >0; Unc_rawALKin    = all(2:end,ismember(header,'Unc_ALK_uM_1sigma'));         Unc_upALKin    = []; for i=1:length(Unc_rawALKin);    if isnumeric(Unc_rawALKin{i});    Unc_upALKin(i,1)    = Unc_rawALKin{i};    else; Unc_upALKin(i,1)    = NaN; end; end; river.observations.ALK_conc_asd    = Unc_upALKin;    river.observations.ALK_equi_asd    = river.observations.ALK_conc_asd    * conc2equi.ALK;    end  
if sum(ismember(header,'Unc_DIC_uM_1sigma'))         >0; Unc_rawDICin    = all(2:end,ismember(header,'Unc_DIC_uM_1sigma'));         Unc_upDICin    = []; for i=1:length(Unc_rawDICin);    if isnumeric(Unc_rawDICin{i});    Unc_upDICin(i,1)    = Unc_rawDICin{i};    else; Unc_upDICin(i,1)    = NaN; end; end; river.observations.DIC_conc_asd    = Unc_upDICin;    river.observations.DIC_equi_asd    = river.observations.DIC_conc_asd    * conc2equi.DIC;    end  
if sum(ismember(header,'Unc_Ca_uM_1sigma'))          >0; Unc_rawCain     = all(2:end,ismember(header,'Unc_Ca_uM_1sigma'));          Unc_upCain     = []; for i=1:length(Unc_rawCain);     if isnumeric(Unc_rawCain{i});     Unc_upCain(i,1)     = Unc_rawCain{i};     else; Unc_upCain(i,1)     = NaN; end; end; river.observations.Ca_conc_asd     = Unc_upCain;     river.observations.Ca_equi_asd     = river.observations.Ca_conc_asd     * conc2equi.Ca;     end   
if sum(ismember(header,'Unc_Mg_uM_1sigma'))          >0; Unc_rawMgin     = all(2:end,ismember(header,'Unc_Mg_uM_1sigma'));          Unc_upMgin     = []; for i=1:length(Unc_rawMgin);     if isnumeric(Unc_rawMgin{i});     Unc_upMgin(i,1)     = Unc_rawMgin{i};     else; Unc_upMgin(i,1)     = NaN; end; end; river.observations.Mg_conc_asd     = Unc_upMgin;     river.observations.Mg_equi_asd     = river.observations.Mg_conc_asd     * conc2equi.Mg;     end   
if sum(ismember(header,'Unc_Na_uM_1sigma'))          >0; Unc_rawNain     = all(2:end,ismember(header,'Unc_Na_uM_1sigma'));          Unc_upNain     = []; for i=1:length(Unc_rawNain);     if isnumeric(Unc_rawNain{i});     Unc_upNain(i,1)     = Unc_rawNain{i};     else; Unc_upNain(i,1)     = NaN; end; end; river.observations.Na_conc_asd     = Unc_upNain;     river.observations.Na_equi_asd     = river.observations.Na_conc_asd     * conc2equi.Na;     end   
if sum(ismember(header,'Unc_K_uM_1sigma'))           >0; Unc_rawKin      = all(2:end,ismember(header,'Unc_K_uM_1sigma'));           Unc_upKin      = []; for i=1:length(Unc_rawKin);      if isnumeric(Unc_rawKin{i});      Unc_upKin(i,1)      = Unc_rawKin{i};      else; Unc_upKin(i,1)      = NaN; end; end; river.observations.K_conc_asd      = Unc_upKin;      river.observations.K_equi_asd      = river.observations.K_conc_asd      * conc2equi.K;      end    
if sum(ismember(header,'Unc_Sr_uM_1sigma'))          >0; Unc_rawSrin     = all(2:end,ismember(header,'Unc_Sr_uM_1sigma'));          Unc_upSrin     = []; for i=1:length(Unc_rawSrin);     if isnumeric(Unc_rawSrin{i});     Unc_upSrin(i,1)     = Unc_rawSrin{i};     else; Unc_upSrin(i,1)     = NaN; end; end; river.observations.Sr_conc_asd     = Unc_upSrin;     river.observations.Sr_equi_asd     = river.observations.Sr_conc_asd     * conc2equi.Sr;     end   
if sum(ismember(header,'Unc_Cl_uM_1sigma'))          >0; Unc_rawClin     = all(2:end,ismember(header,'Unc_Cl_uM_1sigma'));          Unc_upClin     = []; for i=1:length(Unc_rawClin);     if isnumeric(Unc_rawClin{i});     Unc_upClin(i,1)     = Unc_rawClin{i};     else; Unc_upClin(i,1)     = NaN; end; end; river.observations.Cl_conc_asd     = Unc_upClin;     river.observations.Cl_equi_asd     = river.observations.Cl_conc_asd     * conc2equi.Cl;     end   
if sum(ismember(header,'Unc_SO4_uM_1sigma'))         >0; Unc_rawSO4in    = all(2:end,ismember(header,'Unc_SO4_uM_1sigma'));         Unc_upSO4in    = []; for i=1:length(Unc_rawSO4in);    if isnumeric(Unc_rawSO4in{i});    Unc_upSO4in(i,1)    = Unc_rawSO4in{i};    else; Unc_upSO4in(i,1)    = NaN; end; end; river.observations.SO4_conc_asd    = Unc_upSO4in;    river.observations.SO4_equi_asd    = river.observations.SO4_conc_asd    * conc2equi.SO4;    end  
if sum(ismember(header,'Unc_NO3_uM_1sigma'))         >0; Unc_rawNO3in    = all(2:end,ismember(header,'Unc_NO3_uM_1sigma'));         Unc_upNO3in    = []; for i=1:length(Unc_rawNO3in);    if isnumeric(Unc_rawNO3in{i});    Unc_upNO3in(i,1)    = Unc_rawNO3in{i};    else; Unc_upNO3in(i,1)    = NaN; end; end; river.observations.NO3_conc_asd    = Unc_upNO3in;    river.observations.NO3_equi_asd    = river.observations.NO3_conc_asd    * conc2equi.NO3;    end  
if sum(ismember(header,'Unc_PO4_uM_1sigma'))         >0; Unc_rawPO4in    = all(2:end,ismember(header,'Unc_PO4_uM_1sigma'));         Unc_upPO4in    = []; for i=1:length(Unc_rawPO4in);    if isnumeric(Unc_rawPO4in{i});    Unc_upPO4in(i,1)    = Unc_rawPO4in{i};    else; Unc_upPO4in(i,1)    = NaN; end; end; river.observations.PO4_conc_asd    = Unc_upPO4in;    river.observations.PO4_equi_asd    = river.observations.PO4_conc_asd    * conc2equi.PO4;    end  
if sum(ismember(header,'Unc_Si_uM_1sigma'))          >0; Unc_rawSiin     = all(2:end,ismember(header,'Unc_Si_uM_1sigma'));          Unc_upSiin     = []; for i=1:length(Unc_rawSiin);     if isnumeric(Unc_rawSiin{i});     Unc_upSiin(i,1)     = Unc_rawSiin{i};     else; Unc_upSiin(i,1)     = NaN; end; end; river.observations.Si_conc_asd     = Unc_upSiin;     river.observations.Si_equi_asd     = river.observations.Si_conc_asd     * conc2equi.Si;     end   
if sum(ismember(header,'Unc_Ge_uM_1sigma'))          >0; Unc_rawGein     = all(2:end,ismember(header,'Unc_Ge_uM_1sigma'));          Unc_upGein     = []; for i=1:length(Unc_rawGein);     if isnumeric(Unc_rawGein{i});     Unc_upGein(i,1)     = Unc_rawGein{i};     else; Unc_upGein(i,1)     = NaN; end; end; river.observations.Ge_conc_asd     = Unc_upGein;     river.observations.Ge_equi_asd     = river.observations.Ge_conc_asd     * conc2equi.Ge;     end   
if sum(ismember(header,'Unc_Li_uM_1sigma'))          >0; Unc_rawLiin     = all(2:end,ismember(header,'Unc_Li_uM_1sigma'));          Unc_upLiin     = []; for i=1:length(Unc_rawLiin);     if isnumeric(Unc_rawLiin{i});     Unc_upLiin(i,1)     = Unc_rawLiin{i};     else; Unc_upLiin(i,1)     = NaN; end; end; river.observations.Li_conc_asd     = Unc_upLiin;     river.observations.Li_equi_asd     = river.observations.Li_conc_asd     * conc2equi.Li;     end   
if sum(ismember(header,'Unc_F_uM_1sigma'))           >0; Unc_rawFin      = all(2:end,ismember(header,'Unc_F_uM_1sigma'));           Unc_upFin      = []; for i=1:length(Unc_rawFin);      if isnumeric(Unc_rawFin{i});      Unc_upFin(i,1)      = Unc_rawFin{i};      else; Unc_upFin(i,1)      = NaN; end; end; river.observations.F_conc_asd      = Unc_upFin;      river.observations.F_equi_asd      = river.observations.F_conc_asd      * conc2equi.F;      end    
if sum(ismember(header,'Unc_Fe_pM_1sigma'))          >0; Unc_rawFein     = all(2:end,ismember(header,'Unc_Fe_pM_1sigma'));          Unc_upFein     = []; for i=1:length(Unc_rawFein);     if isnumeric(Unc_rawFein{i});     Unc_upFein(i,1)     = Unc_rawFein{i};     else; Unc_upFein(i,1)     = NaN; end; end; river.observations.Fe_conc_asd     = Unc_upFein/1e6; river.observations.Fe_equi_asd     = river.observations.Fe_conc_asd     * conc2equi.Fe;     end   
if sum(ismember(header,'Unc_B_pM_1sigma'))           >0; Unc_rawBin      = all(2:end,ismember(header,'Unc_B_pM_1sigma'));           Unc_upBin      = []; for i=1:length(Unc_rawBin);      if isnumeric(Unc_rawBin{i});      Unc_upBin(i,1)      = Unc_rawBin{i};      else; Unc_upBin(i,1)      = NaN; end; end; river.observations.B_conc_asd      = Unc_upBin/1e6;  river.observations.B_equi_asd      = river.observations.B_conc_asd      * conc2equi.B;      end    
if sum(ismember(header,'Unc_Re_pM_1sigma'))          >0; Unc_rawRein     = all(2:end,ismember(header,'Unc_Re_pM_1sigma'));          Unc_upRein     = []; for i=1:length(Unc_rawRein);     if isnumeric(Unc_rawRein{i});     Unc_upRein(i,1)     = Unc_rawRein{i};     else; Unc_upRein(i,1)     = NaN; end; end; river.observations.Re_conc_asd     = Unc_upRein/1e6; river.observations.Re_equi_asd     = river.observations.Re_conc_asd     * conc2equi.Re;     end   
if sum(ismember(header,'Unc_Mo_pM_1sigma'))          >0; Unc_rawMoin     = all(2:end,ismember(header,'Unc_Mo_pM_1sigma'));          Unc_upMoin     = []; for i=1:length(Unc_rawMoin);     if isnumeric(Unc_rawMoin{i});     Unc_upMoin(i,1)     = Unc_rawMoin{i};     else; Unc_upMoin(i,1)     = NaN; end; end; river.observations.Mo_conc_asd     = Unc_upMoin/1e6; river.observations.Mo_equi_asd     = river.observations.Mo_conc_asd     * conc2equi.Mo;     end   
if sum(ismember(header,'Unc_Os_pM_1sigma'))          >0; Unc_rawOsin     = all(2:end,ismember(header,'Unc_Os_pM_1sigma'));          Unc_upOsin     = []; for i=1:length(Unc_rawOsin);     if isnumeric(Unc_rawOsin{i});     Unc_upOsin(i,1)     = Unc_rawOsin{i};     else; Unc_upOsin(i,1)     = NaN; end; end; river.observations.Os_conc_asd     = Unc_upOsin/1e6; river.observations.Os_equi_asd     = river.observations.Os_conc_asd     * conc2equi.Os;     end  
if sum(ismember(header,'Unc_HCO3_uM_1sigma'))        >0; Unc_rawHCO3in   = all(2:end,ismember(header,'Unc_HCO3_uM_1sigma'));        Unc_upHCO3in   = []; for i=1:length(Unc_rawHCO3in);   if isnumeric(Unc_rawHCO3in{i});   Unc_upHCO3in(i,1)   = Unc_rawHCO3in{i};   else; Unc_upHCO3in(i,1)   = NaN; end; end; river.observations.HCO3_conc_asd   = Unc_upHCO3in;   river.observations.HCO3_equi_asd   = river.observations.HCO3_conc_asd   * conc2equi.HCO3;   end   
if sum(ismember(header,'Unc_d34S_permil_1sigma'))    >0; Unc_rawd34Sin   = all(2:end,ismember(header,'Unc_d34S_permil_1sigma'));    Unc_upd34Sin   = []; for i=1:length(Unc_rawd34Sin);   if isnumeric(Unc_rawd34Sin{i});   Unc_upd34Sin(i,1)   = Unc_rawd34Sin{i};   else; Unc_upd34Sin(i,1)   = NaN; end; end; river.observations.d34S_conc_asd   = Unc_upd34Sin;   river.observations.d34S_equi_asd   = river.observations.d34S_conc_asd   * conc2equi.d34S;   end   
if sum(ismember(header,'Unc_d18O_permil_1sigma'))    >0; Unc_rawd18Oin   = all(2:end,ismember(header,'Unc_d18O_permil_1sigma'));    Unc_upd18Oin   = []; for i=1:length(Unc_rawd18Oin);   if isnumeric(Unc_rawd18Oin{i});   Unc_upd18Oin(i,1)   = Unc_rawd18Oin{i};   else; Unc_upd18Oin(i,1)   = NaN; end; end; river.observations.d18O_conc_asd   = Unc_upd18Oin;   river.observations.d18O_equi_asd   = river.observations.d18O_conc_asd   * conc2equi.d18O;   end   
if sum(ismember(header,'Unc_d7Li_permil_1sigma'))    >0; Unc_rawd7Liin   = all(2:end,ismember(header,'Unc_d7Li_permil_1sigma'));    Unc_upd7Liin   = []; for i=1:length(Unc_rawd7Liin);   if isnumeric(Unc_rawd7Liin{i});   Unc_upd7Liin(i,1)   = Unc_rawd7Liin{i};   else; Unc_upd7Liin(i,1)   = NaN; end; end; river.observations.d7Li_conc_asd   = Unc_upd7Liin;   river.observations.d7Li_equi_asd   = river.observations.d7Li_conc_asd   * conc2equi.d7Li;   end             
if sum(ismember(header,'Unc_d26Mg_permil_1sigma'))   >0; Unc_rawd26Mgin  = all(2:end,ismember(header,'Unc_d26Mg_permil_1sigma'));   Unc_upd26Mgin  = []; for i=1:length(Unc_rawd26Mgin);  if isnumeric(Unc_rawd26Mgin{i});  Unc_upd26Mgin(i,1)  = Unc_rawd26Mgin{i};  else; Unc_upd26Mgin(i,1)  = NaN; end; end; river.observations.d26Mg_conc_asd  = Unc_upd26Mgin;  river.observations.d26Mg_equi_asd  = river.observations.d26Mg_conc_asd  * conc2equi.d26Mg;  end
if sum(ismember(header,'Unc_d30Si_permil_1sigma'))   >0; Unc_rawd30Siin  = all(2:end,ismember(header,'Unc_d30Si_permil_1sigma'));   Unc_upd30Siin  = []; for i=1:length(Unc_rawd30Siin);  if isnumeric(Unc_rawd30Siin{i});  Unc_upd30Siin(i,1)  = Unc_rawd30Siin{i};  else; Unc_upd30Siin(i,1)  = NaN; end; end; river.observations.d30Si_conc_asd  = Unc_upd30Siin;  river.observations.d30Si_equi_asd  = river.observations.d30Si_conc_asd  * conc2equi.d30Si;  end
if sum(ismember(header,'Unc_d42Ca_permil_1sigma'))   >0; Unc_rawd42Cain  = all(2:end,ismember(header,'Unc_d42Ca_permil_1sigma'));   Unc_upd42Cain  = []; for i=1:length(Unc_rawd42Cain);  if isnumeric(Unc_rawd42Cain{i});  Unc_upd42Cain(i,1)  = Unc_rawd42Cain{i};  else; Unc_upd42Cain(i,1)  = NaN; end; end; river.observations.d42Ca_conc_asd  = Unc_upd42Cain;  river.observations.d42Ca_equi_asd  = river.observations.d42Ca_conc_asd  * conc2equi.d42Ca;  end
if sum(ismember(header,'Unc_d44Ca_permil_1sigma'))   >0; Unc_rawd44Cain  = all(2:end,ismember(header,'Unc_d44Ca_permil_1sigma'));   Unc_upd44Cain  = []; for i=1:length(Unc_rawd44Cain);  if isnumeric(Unc_rawd44Cain{i});  Unc_upd44Cain(i,1)  = Unc_rawd44Cain{i};  else; Unc_upd44Cain(i,1)  = NaN; end; end; river.observations.d44Ca_conc_asd  = Unc_upd44Cain;  river.observations.d44Ca_equi_asd  = river.observations.d44Ca_conc_asd  * conc2equi.d44Ca;  end
if sum(ismember(header,'Unc_d56Fe_permil_1sigma'))   >0; Unc_rawd56Fein  = all(2:end,ismember(header,'Unc_d56Fe_permil_1sigma'));   Unc_upd56Fein  = []; for i=1:length(Unc_rawd56Fein);  if isnumeric(Unc_rawd56Fein{i});  Unc_upd56Fein(i,1)  = Unc_rawd56Fein{i};  else; Unc_upd56Fein(i,1)  = NaN; end; end; river.observations.d56Fe_conc_asd  = Unc_upd56Fein;  river.observations.d56Fe_equi_asd  = river.observations.d56Fe_conc_asd  * conc2equi.d56Fe;  end
if sum(ismember(header,'Unc_Sr8786_ratio_1sigma'))   >0; Unc_rawSr8786in = all(2:end,ismember(header,'Unc_Sr8786_ratio_1sigma'));   Unc_upSr8786in = []; for i=1:length(Unc_rawSr8786in); if isnumeric(Unc_rawSr8786in{i}); Unc_upSr8786in(i,1) = Unc_rawSr8786in{i}; else; Unc_upSr8786in(i,1) = NaN; end; end; river.observations.Sr8786_conc_asd = Unc_upSr8786in; river.observations.Sr8786_equi_asd = river.observations.Sr8786_conc_asd * conc2equi.Sr8786; end           
if sum(ismember(header,'Unc_d98Mo_permil_1sigma'))   >0; Unc_rawd98Moin  = all(2:end,ismember(header,'Unc_d98Mo_permil_1sigma'));   Unc_upd98Moin  = []; for i=1:length(Unc_rawd98Moin);  if isnumeric(Unc_rawd98Moin{i});  Unc_upd98Moin(i,1)  = Unc_rawd98Moin{i};  else; Unc_upd98Moin(i,1)  = NaN; end; end; river.observations.d98Mo_conc_asd  = Unc_upd98Moin;  river.observations.d98Mo_equi_asd  = river.observations.d98Mo_conc_asd  * conc2equi.d98Mo;  end            
if sum(ismember(header,'Unc_Os187188_ratio_1sigma')) >0; Unc_rawOs8788in = all(2:end,ismember(header,'Unc_Os187188_ratio_1sigma')); Unc_upOs8788in = []; for i=1:length(Unc_rawOs8788in); if isnumeric(Unc_rawOs8788in{i}); Unc_upOs8788in(i,1) = Unc_rawOs8788in{i}; else; Unc_upOs8788in(i,1) = NaN; end; end; river.observations.Os8788_conc_asd = Unc_upOs8788in; river.observations.Os8788_equi_asd = river.observations.Os8788_conc_asd * conc2equi.Os8788; end            
if sum(ismember(header,'Unc_d13C_permil_1sigma'))    >0; Unc_rawd13Cin   = all(2:end,ismember(header,'Unc_d13C_permil_1sigma'));    Unc_upd13Cin   = []; for i=1:length(Unc_rawd13Cin);   if isnumeric(Unc_rawd13Cin{i});   Unc_upd13Cin(i,1)   = Unc_rawd13Cin{i};   else; Unc_upd13Cin(i,1)   = NaN; end; end; river.observations.d13C_conc_asd   = Unc_upd13Cin;   river.observations.d13C_equi_asd   = river.observations.d13C_conc_asd   * conc2equi.d13C;   end            
if sum(ismember(header,'Unc_Fmod_1sigma'))           >0; Unc_rawFmodin   = all(2:end,ismember(header,'Unc_Fmod_1sigma'));           Unc_upFmodin   = []; for i=1:length(Unc_rawFmodin);   if isnumeric(Unc_rawFmodin{i});   Unc_upFmodin(i,1)   = Unc_rawFmodin{i};   else; Unc_upFmodin(i,1)   = NaN; end; end; river.observations.Fmod_conc_asd   = Unc_upFmodin;   river.observations.Fmod_equi_asd   = river.observations.Fmod_conc_asd   * conc2equi.Fmod;   end            

% (4) calculate and save the sums of Na+K, Ca+Mg, Mg+Na, and Ca+Na. these are generally just extra variables, but can be useul when plotting ternary diagrams
river.observations.NaK_conc  = river.observations.Na_conc + river.observations.K_conc;  river.observations.NaK_equi  = river.observations.Na_conc*conc2equi.Na + river.observations.K_conc*conc2equi.K;
river.observations.CaMg_conc = river.observations.Ca_conc + river.observations.Mg_conc; river.observations.CaMg_equi = river.observations.Ca_conc*conc2equi.Ca + river.observations.Mg_conc*conc2equi.Mg;
river.observations.MgNa_conc = river.observations.Mg_conc + river.observations.Na_conc; river.observations.MgNa_equi = river.observations.Mg_conc*conc2equi.Mg + river.observations.Na_conc*conc2equi.Na;
river.observations.CaNa_conc = river.observations.Ca_conc + river.observations.Na_conc; river.observations.CaNa_equi = river.observations.Ca_conc*conc2equi.Ca + river.observations.Na_conc*conc2equi.Na;
